on: push
name: Build release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build zip file
      uses: lafernando/github-action-bash@v1.0
      args: IyEvYmluL2Jhc2ggLSAKIz09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KIwojICAgICAgICAgIEZJTEU6IGJ1aWxkLnNoCiMgCiMgICAgICAgICBVU0FHRTogLi9idWlsZC5zaCAKIyAgICAgICAgQVVUSE9SOiBBdml5YW0gRmlzY2hlciAoKSwgCiMgICAgICAgQ1JFQVRFRDogMDMvMTIvMjAyMyAwNjowMzoxMiBQTQojICAgICAgUkVWSVNJT046ICAtLS0KIz09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KCnRyYXAgX2NsZWFudXAgU0lHVEVSTQoKX2NsZWFudXAoKSB7CgllY2hvCiBybSAtcmYgYnVpbGQKfQoKbWtkaXIgLi9idWlsZApmaW5kIC4gLW1heGRlcHRoIDEgLW5vdCAtbmFtZSAnLionIC10eXBlIGYgIC1leGVjIGNwIC12IHt9IC4vYnVpbGQvIFw7IApjcCAtdnIgLi9pY29ucyBidWlsZC8Kcm0gYnVpbGQvYnVpbGQuc2gKdmVyc2lvbj0kKGNhdCBtYW5pZmVzdC5qc29uIHwganEgLXIgLnZlcnNpb24pClsgLWQgImRpc3QiIF0gfHwgbWtkaXIgZGlzdAp6aXAgIC1yIGRpc3QvaGFycGFnb25fJHZlcnNpb24uemlwIGJ1aWxkIAo=
