on: push
name: Build release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: zip
      uses: TheDoctor0/zip-release@0.7.1
      with:
        exclusions: |
          build.sh
          .gitignore 
          .git
    
