on: push

jobs:
  runscript:
    name: 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Call a Bash Script
        run:  |
          mkdir  ./build
          mkdir ./dist
          find . -maxdepth 1 -not -name '.*' -type f  -exec cp -v {} ./build/ \; 
          cp -r ./icons ./build/
          rm build/build.sh
          echo "CRX_VERSION=$(cat manifest.json | jq -r .version)" >> $GITHUB_ENV
        shell: bash

      - id: packExtensionDir
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: 'build'
          zipFilePath: 'dist/extension.zip'
      
      - uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          
          zipFilePath: 'dist/extension.zip'
          crxFilePath: 'dist/harpagon_${{ env.CRX_VERSION }}.crx'
          privateKey: ${{ secrets.HARPAGON_PEM }}
          # The following is optional if you need update.xml file
          # updateXmlPath: 'build/update.xml'
          # updateXmlCodebaseUrl: 'https://server.com/extension.crx'


      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.CRX_VERSION }} 
          files: |
            dist/harpagon_${{ env.CRX_VERSION }}.crx
        env:
          GITHUB_TOKEN: ${{ secrets.HARPAGON_TOKEN }}
